export var numberButtons = document.querySelectorAll(".NumberButton")
export var OperationButton = document.querySelectorAll(".OperationButton")
export var ActionButton = document.querySelectorAll(".ActionButton")
export var MainDisplay = document.getElementById("NumberDisplay")
export var SecondDisplay = document.getElementById("SecondDisplay")